# Generated by Django 5.0.1 on 2025-05-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
